---
title: "Evaluating Sacharomyces cell cycle genes"
output: html_notebook
---

```{r setup}
  options(java.parameters = "-Xmx2048m")
  develRun = TRUE;
```

First we install and start all the required libraries.

```{r}
  # Helper function to install packages if they are not available
  pkgTest <- function(x)
  {
    if (!require(x,character.only = TRUE))
    {
      install.packages(x,dep=TRUE)
        if(!require(x,character.only = TRUE)) stop("Package not found")
    }
  }

  # Install and load the packages required for evaluation against TD-Aracne
  if(!develRun) {
    source("https://bioconductor.org/biocLite.R")
    biocLite(c("Biobase","TDARACNE", "RBGL"))
  }
  library(Biobase)
  library(TDARACNE)
  library(RBGL)
  
  pkgTest("splines")
  pkgTest("foreach")
  pkgTest("doParallel")
  pkgTest("rJava")
  pkgTest("tidyverse")
  
  # Install and load Genexpi from GitHub vie devtools
  if(!develRun) {
    pkgTest("devtools")
    install_github("cas-bioinf/genexpi", ref = "bmc-release", subdir="rpackage")
  }

  
```



```{r}
yeastract_file <- 'yeastract.tsv.gz'
if(!file.exists(yeastract_file)) {
  download.file("http://www.yeastract.com/download/RegulationTwoColumnTable_Documented_2013927.tsv.gz", yeastract_file)
}

yeastract_df <- read.delim(gzfile(yeastract_file),sep = ";",header = FALSE, col.names = c("regulator","target"))
```



```{r}
gds38_file <- 'gds38.soft.gz';
if(!file.exists(gds38_file)) {
  download.file("ftp://ftp.ncbi.nlm.nih.gov/geo/datasets/GDSnnn/GDS38/soft/GDS38_full.soft.gz", gds38_file)
}

#Intermediate data frame representation
gds38_raw_df = read.delim(gzfile(gds38_file), skip = 149, comment.char = "!", na.strings = c("null","")) 

```

```{r}

#SWI4/6, MBP1 a re suspect as they act in complexes (BTW good test case for the cooperative model)
regulators <- c("FKH1", "FKH2","MCM1","MBP1","SWI4","SWI6","NDD1", "ACE2")
#regulators <- c("FKH1", "FKH2","MCM1","MBP1","SWI4","SWI6", "ACE2")
yeastract_filtered <- yeastract_df%>% filter(regulator %in% regulators) %>%
  filter(target %in% gds38_raw_df$IDENTIFIER) %>%
  group_by(regulator) 

all_targets <- as.character(yeastract_filtered$target)
genes_of_interest <- unique(as.character(c(regulators, all_targets)))

gds38_raw <- aggregate(gds38_raw_df[,3:18], gds38_raw_df["IDENTIFIER"], mean, na.rm = TRUE) %>%
  column_to_rownames("IDENTIFIER") %>%
  as.matrix() %>% exp()
  
gds38_raw_filtered <- gds38_raw[genes_of_interest,]

#Exclude all that contain only NA
#gds38_raw <- gds38_raw[apply(gds38_raw, 1, function(x) { sum(!is.na(x)) > 5}),]

time_raw <- seq(0,by = 7, length.out = 16)
time_smooth <- 0:max(time_raw)
```

```{r}
splineDF = 5
gds38_smooth_filtered <- splineProfileMatrix(gds38_raw_filtered, time_raw, time_smooth, df = splineDF, intercept = TRUE)
inspectSmoothing(time_raw, gds38_raw_filtered,time_smooth, gds38_smooth_filtered, c("ACE2","FKH2"))

```


```{r}
errorDef <- defaultErrorDef()
errorDef$relative <- 0.1
errorDef$minimal <- 0.2
deviceSpecs <- getDeviceSpecs(2)
minFitQuality <- 0.8
randomRounds <- 3
```

#Filter out constant synthesis
```{r}
regulators_logical <- rownames(gds38_smooth_filtered) %in% regulators 
constantProfiles = testConstant(gds38_smooth_filtered, errorDef)
profilesToTestConstantSynthesisIndices = which(!constantProfiles & !regulators_logical)

constantSynthesisResults = computeConstantSynthesis(deviceSpecs, gds38_smooth_filtered, tasks = profilesToTestConstantSynthesisIndices);

constantSynthesisProfiles = testConstantSynthesis(constantSynthesisResults, errorDef, minFitQuality);

profilesToTest_logical <- regulators_logical | (!constantProfiles & !constantSynthesisProfiles)

gds38_raw_to_test <- gds38_raw_filtered[profilesToTest_logical,]
gds38_smooth_to_test <- gds38_smooth_filtered[profilesToTest_logical,]

profilesToTest <- rownames(gds38_smooth_filtered[profilesToTest_logical])
```

#Test random with Genexpi

```{r}
randomScale = 1.6
randomLength = 10
plotRandomProfiles(20, time_raw, scale = randomScale, length = randomLength,trueTime = time_raw,  trueProfile = gds38_raw["ACE2",])
plotRandomProfiles(20, time_raw, scale = randomScale, length = randomLength,trueTime = time_raw,  trueProfile = gds38_raw["FKH1",])
plotRandomProfiles(20, time_raw, scale = randomScale, length =                randomLength,trueTime = time_raw,  trueProfile = gds38_raw["SWI4",])
```


```{r}
results_genexpi <- list()
for(regulator_to_test in regulators) {
  cat("======", regulator_to_test, "=====\n")
  regulon_to_test <- yeastract_filtered %>% filter(regulator == regulator_to_test) %>%  # Using get to take refer to the regulator local variabl (not the column)
    get("target", .) %>% as.character()
  evaluation_res <- evaluateRandomForRegulon(deviceSpecs = deviceSpecs,rawProfiles = gds38_raw_to_test, rounds = randomRounds, regulatorName = regulator_to_test, regulonNames = regulon_to_test, checkConstantSynthesis = FALSE, time = time_smooth, rawTime = time_raw, randomScale = randomScale, randomLength = randomLength, splineDFs = splineDF, splineIntercept = TRUE, errorDef = errorDef)
  cat("True ratio: ", evaluation_res$trueRatio,"\n")
  cat("Mean random ratio: ", mean(evaluation_res$randomRatios), "\n")
  results_genexpi[[regulator_to_test]] <- evaluation_res
}
```

```{r}
results_aracne <- list()
for(regulator_to_test in regulators) {
  cat("======", regulator_to_test, "=====\n")
  regulon_to_test <- yeastract_filtered %>% filter(regulator == regulator_to_test) %>%  # Using get to take refer to the regulator local variabl (not the column)
    get("target", .) %>% as.character()
  res_aracne <- evaluateTDAracne(randomRounds, gds38_raw, time_raw, c(splineDF), time_smooth, randomScale, randomLength, regulatorName = regulator_to_test, regulonNames = regulon_to_test, errorDef = errorDef, numBins = 10)
  results_aracne[[regulator_to_test]] <- res_aracne
}
```
```{r}
results_aracne_formatted <- list()
step = 1
for(regulator in regulators) {
  evaluationResult <- results_aracne[[regulator]]
  results_aracne_formatted[[step]] <- data.frame(regulator = regulator, type = "Downstream", true = evaluationResult$trueRatioDownstream, random = evaluationResult$overallRandomRatioDownstream)
  step <- step + 1
  results_aracne_formatted[[step]] <- data.frame(regulator = regulator, type = "Connected", true = evaluationResult$trueRatioConnected, random = evaluationResult$overallRandomRatioConnected)
  step <- step + 1
}

results_aracne_formatted <- do.call(rbind, results_aracne_formatted)
results_aracne_formatted
```

```{r}
g = "ACE2"
matplot(t(gds38_raw[rownames(gds38_raw) == g,, drop = FALSE]), type = "l")
matplot(log(t(gds38_raw[rownames(gds38_raw) == g,, drop = FALSE])), type = "l")
```

#Backup access to GSE24771

```{r}
temp_gse24771 <- tempfile();
#download.file("https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE24771&format=file&file=GSE24771%5Fcomplete%5Fnormalized%2Etxt%2Egz", temp)

download.file("ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE24nnn/GSE24771/suppl/GSE24771_complete_normalized.txt.gz", temp_gse24771)


gse24771_raw_df = read.delim(gzfile(temp_gse24771)) 
```

```{r}
gse24771_tidy <- gse24771_raw_df %>% 
  gather("sample","expression", -ID_REF) %>% 
  mutate(time = as.integer(gsub("^[^.]*\\.T([0-9]*)","\\1", sample)), 
         sample = gsub("^([^.]*)\\.T[0-9]*","\\1", sample))
```


```{r}
genes = c("YFL021W","YLR131C","YNL068C") #GAT1, ACE2, FKH2
gse24771_tidy %>% 
  filter(ID_REF %in% genes) %>%
  ggplot(aes(x = time, y = expression, color = sample)) + geom_line() + facet_wrap( ~ ID_REF, ncol = 1, scales = "free")

# gse24771_tidy %>% 
#   filter(ID_REF == gene) %>% 
#   summarise(m = mean(expression), s = sd(expression))

```


